### ISSUE TITLE
Release strategy

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#125]
In order to be able to publish the package we need a release strategy and also include proper versioning of the code and documentation.

**Comment by fzimmermann89** [comment]
We should really get a simple relase to pypi working.
My suggestion would be to follow the [python docu example](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/) and release each push to main to testpypi and each tagged release to pypi.
I would, for now, stay with[ 0.*-versioning](https://semver.org/lang/de/#spec-item-4), do weekly-if-anything-changed releases to pypi with version 0.YYWW until we have some stability in the interfaces.

Also, I would like to be added as maintainer to pypi @ckolbPTB @schuenke :)

**Comment by schuenke** [comment]
@fzimmermann89 : I added you as maintainer/owner on PyPi and TestPyPi.

I can try to get the CD pipeline done before my vacation. But we need to agree on the release and versioning scheme. 

@ckolbPTB do you agree with:

1. each push to main will be released to TestPyPi
2. each tagged push will be released to PyPi
3. we use the following versioning scheme until the first stable release: `0.YY.MMDD` (if we have more than one release to TestPyPi on the same day, we need to add another `-revN` etc)
4. we create tagged pushes every week (or every 2 weeks) automatically until the first  stable release
5. after the first stable release, we swtich so semantic versioning

**Comment by ckolbPTB** [comment]
Fine by me. 

We often have small issues which dependent on each other so multiple push to main in one day will occur.

**Comment by fzimmermann89** [comment]
We could also do 0.commitnumber both on pypi and Testpypi?

**Comment by schuenke** [comment]
Independent of the versioning scheme, we have to figure out how to automatically bump the version in the pyproject.toml file without triggering all the other actions again. 

Or do we actually want to keep the version in the pyproject.toml untouched for TestPyPi releases and just change it when doing tagged pushes that trigger the deployment to PyPi? 

In this case, we could  just temporarily overwrite the version in the pyproject.toml file before the build step (without pushing it) to ensure we have increasing version numbers on TestPyPi, which is necessary because you cannot have another release with the same version number.

**Comment by fzimmermann89** [comment]
https://setuptools-git-versioning.readthedocs.io/en/stable/substitutions/ccount.html

**Comment by schuenke** [comment]
We now decided to trigger a release only when the VERSION file is changed. If this happens in a dev branch, it will lead only to a deployment to TestPyPi. When beeing squash-merged to main, it will trigger a release to TestPyPi and PyPi. See #439 .
