### ISSUE TITLE
IData class

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#2]
```
class IData():
    IData.header (based on ismrmrd) -> check in functions if certain parameters are available
    IData.data: torch.Tensor 5D: [everything_else, coils, z, y, x]

from_kdata()
   from_ismrmrd()
   from_nifty()
   from_dicom()
```

Check list:
- [x]     Create branch
- [x]     Implement code
- [x]     Add comments
- [x]     Implement tests
- [x]     Squash commmits
- [x]     Create PR
- [x]     Assign reviewer(s) to PR

**Comment by schuenke** [comment]
Currently the IHeader attributes are:

- fov
- TE
- TR
- TI
- flip angle

Should we add the matrix / image dimension as attribute? This would:

1. allow to calculate the resolution solely from header information (currently we need IData.header.fov and IData.data.shape to do this)
2. allow us to check if header infos and data match, when we create an IData obj from a KData obj (using the IData.from_kdata() classmethod). For KData we ensure that the header infos and data match, but ofc it would be possible to modify the KData obj afterwards...

**Comment by fzimmermann89** [comment]
Do we plan on making IData frozen?
If yes, I think this would prevent changing the data shape later on (as you would have to set a new tensor to change the shape). If no, we would have to also check/update on setting new data if the shape matches or update the shape.


I think the goal should be to have stuff match automatically by not having redundancies instead of checking if two properties are set to the same value. I.e. being able to check if they match is not a pro argument for storing .shape, but a contra argument is that you would have to check that they match...

We could also just have an read-only property shape, that returns the .data.shape ?
Then these match automatically?



PS: I'd still prefer to have `resolution` (instead of FOV) as the stored property.
In images, it makes sense (IMHO) to be able to crop and not having the change the header?

**Comment by schuenke** [comment]
Okay, I am fine with leaving the shape out of the IHeader. If we later realize we need/want it, we can still add it afterwards.

Adding a shape property to IData could be convenient, but it would be the same for FOV/resolution, no?! Thus I would either add both or none. 

For FOV vs resolution I would suggest to open an issue/ poll.
