### ISSUE TITLE
Rounding vs truncating of trajectory

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#285]
In https://github.com/PTB-MR/mrpro/blob/d15579a27c650131d94ca9b058f4d6583293b4d4/src/mrpro/operators/_CartesianSamplingOp.py#L62 we truncate, not round the trajectory. so 0.99 -> 0.
Also in  https://github.com/PTB-MR/mrpro/blob/67a31834ea6d7adebb757de03818c488230c269b/src/mrpro/data/_KTrajectory.py#L159 we check on_grid by the fraction, so 0.999 will not be considered as on_grid.

We should change both.

**Comment by ckolbPTB** [comment]
yes, we should round before calling .to(int). 

What is the problem of https://github.com/PTB-MR/mrpro/blob/67a31834ea6d7adebb757de03818c488230c269b/src/mrpro/data/_KTrajectory.py#L159 ?

EDIT: I see what you mean. 5.9999 would not be considered on_grid because 0.9999 <= tolerance but we should actually check (6.5.9999) <= tolerance.
