### ISSUE TITLE
Protect main?

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#94]
Consider protecting main and enforcing that the tests succeed before merging into main.

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches

**Comment by fzimmermann89** [comment]
This would also mean moving main into the public repo.
And only having development branches in the private repo.
(Or paying for github pro)

**Comment by schuenke** [comment]
I support the idead to protect main, but not sure whats the best way to handle it. 

We discussed before that it might make sense to move the whole private repo to the public one so that the complete Issue / PR history is available in the public repo and use the private repo only for new (and unpublished) feature development, but I am not sure if everyone agrees with this.

Maybe we can discuss it tomorrow in the meeting?!

**Comment by fzimmermann89** [comment]
Solved by moving the repo to PTB-MR.
